BlogMVC/Models/BlogDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace BlogMVC.Models
{
    public class BlogDbContext: DbContext
    {
        public DbSet<Post> Posts { get; set; }
        public DbSet<Category> Categories { get; set; }
        public BlogDbContext(DbContextOptions<BlogDbContext> options)
            : base(options)
        {
            Database.EnsureCreated();
        }
    }
  
}

BlogMVC/Models/Category.cs
namespace BlogMVC.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Title { get; set; } 
        public string? Description { get; set; }
    }
}

BlogMVC/Models/ErrorViewModel.cs
namespace BlogMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlogMVC/Models/Post.cs
namespace BlogMVC.Models
{
    public class Post
    {     
    public int Id { get; set; }
    public string? Title { get; set; } 
    public DateTime PublishDate { get; set; } 
    public string? Description { get; set; } = string.Empty;
    public bool IsDraft { get; set; } 
    public string? Content { get; set; }
    public int? CategoryId  { get; set; }
    public virtual Category? Category { get; set; }
    }
}

BlogMVC/Models/PostsFiltrModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlogMVC.Models
{
    public class PostsFiltrModel
    {
        public IEnumerable<Post> Posts { get; set; } = new List<Post>();
        public SelectList Categories { get; set; } =   new SelectList(new List<Category>(), "Id", "Title");
    }
}

BlogMVC/Controllers/AdminController.cs
using BlogMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BlogMVC.Controllers
{
    public class AdminController : Controller
    {
        BlogDbContext db;
        public AdminController(BlogDbContext context)
        {
            db = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Categories = db.Categories;
            var posts = await db.Posts.Include(c => c.Category).ToListAsync();
            return View(posts);
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCategory(Category category)
        {
            db.Categories.Add(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditCategory(int? id)
        {
            if(id != null) 
            {
                Category? category = await db.Categories.FirstOrDefaultAsync(c => c.Id == id);
                if (category != null) return View(category);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditCategory(Category category)
        {
            db.Categories.Update(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public IActionResult CreatePost()
        {
            ViewBag.Categories = db.Categories;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(Post post)
        {
            db.Posts.Add(post);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id != null)
            {
                Post? post = await db.Posts.FirstOrDefaultAsync(p => p.Id == id);
                if (post != null)
                {
                    db.Posts.Remove(post);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }
        public async Task<IActionResult> EditPost(int? id)
        {
            ViewBag.Categories = db.Categories;
            if (id != null)
            {
                Post? post = await db.Posts.FirstOrDefaultAsync(p => p.Id == id);
                if (post != null) return View(post);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(Post post)
        {
            db.Posts.Update(post);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

BlogMVC/Controllers/BlogController.cs
using BlogMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BlogMVC.Controllers
{
    public class BlogController : Controller
    {
        BlogDbContext db;
        public BlogController(BlogDbContext context)
        {
            db = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult ViewPosts(int category)
        {
            IQueryable<Post> posts = db.Posts.Include(p => p.Category).Where(d => !d.IsDraft);
            if (category != null && category != 0)
            {
                posts = posts.Where(p => p.CategoryId == category);
            }

            List<Category> categories = db.Categories.ToList();
      
            categories.Insert(0, new Category { Title = "Все", Id = 0 });

            PostsFiltrModel viewModel = new PostsFiltrModel
            {
                Posts = posts.ToList(),
                Categories = new SelectList(categories, "Id", "Title", category)
            };
            return View(viewModel);
        }

        public async Task<IActionResult> ViewPost(int id)
        {
            Post post;
            try
            {
                post = await db.Posts.Include(c => c.Category).SingleAsync(i => i.Id == id);
            }
            catch (Exception e)
            {
                return NotFound();
            }
            return View(post);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlogMVC/Views/Admin/CreateCategory.cshtml
@model Category

<h2>Добавление категории</h2>
<form asp-action="CreateCategory" asp-controller="Admin">
    <p>
        <label asp-for="Title">Название категории</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Description">Описание категории</label><br />
        <input type="text" asp-for="Description" />
    </p>

    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

BlogMVC/Views/Admin/CreatePost.cshtml
@model Post
<h2>Добавление статьи</h2>
<form asp-action="CreatePost" asp-controller="admin">
    <p>
        <label asp-for="Title">Название статьи</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="PublishDate">Дата публикации</label><br />
        <input asp-for="PublishDate" type="date" class="form-control" />
    </p>
    <p>
        <label asp-for="Description">Описание статьи</label><br />
        <textarea asp-for="Description" class="form-control"></textarea>
    </p>
    <p>
        <label asp-for="Content">Содержание статьи</label><br />
        <textarea asp-for="Content" class="form-control"></textarea>
    </p>
    <p>
        <select asp-for="CategoryId">
            @foreach (Category category in ViewBag.Categories)
            {
                <option value="@category.Id">@category.Title</option>
            }
        </select>
    </p>
    <p>
        <label>
            <input asp-for="IsDraft" type="checkbox" />
            черновик
        </label>
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

BlogMVC/Views/Admin/EditCategory.cshtml
@model Category

<h2>Редактирование категории</h2>
<form asp-action="EditCategory" asp-controller="Admin" asp-route-id = "@Model.Id">
    <p>
        <label asp-for="Title">Название категории</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="Description">Описание категории</label><br />
        <input type="text" asp-for="Description" />
    </p>

    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

BlogMVC/Views/Admin/EditPost.cshtml
@model Post
<h2>Редактирование статьи</h2>
<form asp-action="EditPost" asp-controller="Admin" asp-route-id="@Model.Id">
    <p>
        <label asp-for="Title">Название статьи</label><br />
        <input type="text" asp-for="Title" />
    </p>
    <p>
        <label asp-for="PublishDate">Дата публикации</label><br />
        <input asp-for="PublishDate" type="date" class="form-control" />
    </p>
    <p>
        <label asp-for="Description">Описание статьи</label><br />
        <textarea asp-for="Description" class="form-control"></textarea>
    </p>
    <p>
        <label asp-for="Content">Содержание статьи</label><br />
        <textarea asp-for="Content" class="form-control"></textarea>
    </p>
    <p>
        <select asp-for="CategoryId">

            @foreach (Category category in ViewBag.Categories)
            {
                <option value="@category.Id">@category.Title</option>
            }

        </select>
    </p>
    <p>
        <label>
            <input asp-for="IsDraft" type="checkbox" />
            черновик
        </label>
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
</form>

BlogMVC/Views/Admin/Index.cshtml
<br />
<a class="btn btn-lg btn-primary" asp-action="CreateCategory">Добавить категорию</a>
<a class="btn btn-lg btn-primary" asp-action="CreatePost">Добавить статью</a>
<br />
<br />
<h3>Категории</h3>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Название</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Category category in ViewBag.Categories)
        {
            <tr>
                <td>
                    @category.Title
                </td>
                <td>
                    <a class="btn-sm btn-primary" asp-action="EditCategory" asp-route-id="@category.Id">Изменить</a>
                </td>
            </tr>
        }

    </tbody>
</table>
<br />

<h3>Черновики</h3>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Заголовок</th>
            <th>Категория</th>
            <th>Дата</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
            if (p.IsDraft == true)
            {
                <tr>
                    <td>@p.Title</td>
                    @{
                        if (p.CategoryId != null)
                        {
                            <td>@p.Category.Title</td>
                        }
                        else
                        {
                            <td>без категории</td>
                        }
                    }
                    <td>@p.PublishDate.ToShortDateString()</td>
                    <td style="display:flex">
                        <a class="btn-sm btn-primary" asp-action="EditPost" asp-route-id="@p.Id">Изменить</a>

                        <form method="post" asp-action="DeletePost" asp-route-id="@p.Id" class="pull-right">
                            <input type="hidden" name="id" value="@p.Id" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                &times;
                            </button>
                        </form>
                    </td>
                </tr>
            }

        }
    </tbody>
</table>



<br />



<h3>Опубликованные статьи</h3>
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Заголовок</th>
            <th>Категория</th>
            <th>Дата</th>
            <th>Действия</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var p in Model)
        {
            if (p.IsDraft == false)
            {
                <tr>
                    <td>@p.Title</td>
                    @{
                        if (p.CategoryId != null)
                        {
                            <td>@p.Category.Title</td>
                        }
                        else
                        {
                            <td>без категории</td>
                        }

                    }
                    <td>@p.PublishDate.ToShortDateString()</td>
                    <td style="display:flex">
                        <a class="btn-sm btn-primary" asp-action="EditPost" asp-route-id="@p.Id">Изменить</a>

                        <form method="post" asp-action="DeletePost" asp-route-id="@p.Id" class="pull-right">
                            <input type="hidden" name="id" value="@p.Id" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                &times;
                            </button>
                        </form>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

BlogMVC/Views/Blog/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать в блог foodrink!</h1>
    
</div>
<header class="masthead" style="background-image: url('~/../../assets/img/aboutt-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-9">
                <div class="page-heading">
                    <h1>Информация о блоге</h1>
                   
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-9 px-lg-7">
        <div class="row gx-6 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg18 col-xl-7">  
                <p align="justify">
                    Привет! Я Hoodwink! Я фотограф. И,конечно же, большой любитель вкусно поесть.  </p>
                <p align="center"> <b> НЕМНОГО ОБО МНЕ</b></p>
                <p align="justify">
                    Я занимаюсь фотографией с тех пор, как мне исполнилось 12 лет. Я переехал в Калифорнию в 2012 году, чтобы поступить в колледж дизайна Art Center.
                За эти годы я сделал тысячи снимков еды.
                    Я также провел несколько выступлений и семинаров в колледжах, фотоконференциях, конференциях по ведению кулинарных блогов, онлайн-саммитах, вебинарах и кулинарных конференциях по всей территории США.
                </p>
                
        </div>
    </div>
</main>

BlogMVC/Views/Blog/ViewPost.cshtml
@model Post
<h1>@Model.Title</h1>
<p>@Model.Category.Title</p>
<p>@Model.PublishDate.ToShortDateString()</p>
<p>@Model.Content</p>

BlogMVC/Views/Blog/ViewPosts.cshtml
<form method="get">
    <div>
        <label>Категория: </label>
        <select name="category" asp-items="Model.Categories"></select>

        <input type="submit" value="Сортировать" />
    </div>
</form>

<h2>Посты</h2>
@foreach (var p in Model.Posts)
{
    <h3>@p.Title</h3>
    <p>@p.Category.Title</p>
    <p>@p.PublishDate.ToShortDateString()</p>
    <p>@p.Description</p>
    <p>
        <a class="btn-sm btn-primary" asp-action="ViewPost" asp-route-id="@p.Id">Читать статью</a>
    </p>
}

BlogMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -fooddrink</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogMVC.styles.css" asp-append-version="true" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Blog" asp-action="Index">BlogMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">О нас</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="ViewPosts">Статьи</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
        </ul>
        <p class="text-center text-body-secondary">© 2023</p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>